// SPDX-License-Identifier: GPL-3.0-or-later or MIT
/*
 * Copyright 2025 Jiamu Sun <barroit@linux.com>
 */

/*
 * Was this fucking win32 directory related API/errno design generated by a
 * monkey smashing a keyboard?
 */

#include "mkdir.h"

#include <windows.h>

#include "path.h"
#include "termas.h"
#include "xalloc.h"
#include "xcf.h"

int __mkdirp(xchar *buf)
{
	int err;
	int start = 0;
	DWORD attr;
	xchar __sep;
	xchar *sep = pth_next_sep(buf);

	if (pth_is_abs(sep)) {
		while (chr_is_sep(sep[1]))
			sep++;
		sep = pth_next_sep(&sep[1]);
	}

	while (sep) {
		__sep = *sep;
		*sep = 0;

		if (!start) {
			attr = GetFileAttributes(buf);

			if (attr == INVALID_FILE_ATTRIBUTES)
				start = 1;
			else if (!(attr & FILE_ATTRIBUTE_DIRECTORY))
				goto err_not_dir;
			else
				goto next;
		}

		err = !CreateDirectory(buf, NULL);
		if (err)
			goto err_out;

next:
		*sep = __sep;
		while (chr_is_sep(sep[1]))
			sep++;

		if (!sep[1])
			return 0;
		sep = pth_next_sep(&sep[1]);
	}

	err = !CreateDirectory(buf, NULL);
	if (!err)
		return 0;

err_out:
	errno = winerrno();

	if (!start) {
		attr = GetFileAttributes(buf);

		if (attr != INVALID_FILE_ATTRIBUTES &&
		    !(attr & FILE_ATTRIBUTE_DIRECTORY)) {
err_not_dir:
			errno = ENOTDIR;
		}
	}

	return -1;
}

int mkdirp(const xchar *name)
{
	xchar *buf = xc_strdup(name);
	int ret = __mkdirp(buf);

	free(buf);
	return ret;
}
